<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Comments\Responses\" />
    <Folder Include="Images\Responses\" />
    <Folder Include="Addresses\Responses\" />
    <Folder Include="Products\Responses\" />
    <Folder Include="Auths\Requests\" />
    <Folder Include="Auths\Responses\" />
    <Folder Include="Rating\Responses\" />
    <Folder Include="Users\Requests\" />
    <Folder Include="Users\Responses\" />
    <Folder Include="Tags\Responses\" />
    <Folder Include="Categories\Responses\" />
  </ItemGroup>

</Project>
